name: fehu
description: Fehu - Streaming Payments

# Remove this line if you wish to publish to pub.dev
publish_to: 'none'

# The version and build number for the application.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # UI components
  cupertino_icons: ^1.0.2

  # State management
  stacked: ^3.0.0
  stacked_themes: ^0.3.9
  intl: ^0.17.0
  http: ^0.13.5
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package encourages good coding practices.
  flutter_lints: ^2.0.0

  # Flutter Launcher Icons is a command-line tool which simplifies the task
  # of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  adaptive_icon_background: "#000000"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Asset directory paths:
  assets:
    - assets/icons/
    - assets/images/

  # Custom fonts
  fonts:
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Light.ttf
          weight: 300
        - asset: fonts/Rajdhani-Regular.ttf
          weight: 400
        - asset: fonts/Rajdhani-Medium.ttf
          weight: 500
        - asset: fonts/Rajdhani-SemiBold.ttf
          weight: 600
        - asset: fonts/Rajdhani-Bold.ttf
          weight: 700
